---
- name: Get kubefile
  command: >-
    cp "{{ contentrepo+'/'+uid+'/'+req_id }}/kubeconfig.zip"
    "{{ work_dir }}/kubeconfig.zip"
  tags: "kubeconfig"

- name: Unpack kubeconfig files
  unarchive:
    src: "{{ work_dir }}/kubeconfig.zip"
    dest: "{{ work_dir }}/kube"
  tags: "kubeconfig"

- name: Ensure vars directory exists
  file:
    path: "{{ work_dir }}/../vars"
    state: "{{ item }}"
  with_items:
    - directory

- name: Rename kubeconfig file
  shell: >-
    find . -name kube*.yml|cat -n|while read n f; do cp "$f" "../../vars/kubeconfig"; done
  args:
    chdir: "{{ work_dir }}/kube"
  ignore_errors: yes
  tags: "kubeconfig"

- name: Copy kube cert to the right place
  shell: >-
    find . -name *.pem -type f -print | xargs cp --target-directory=../../vars
  args:
    chdir: "{{ work_dir }}/kube"
  ignore_errors: yes
  tags: "kubeconfig"
