{
 "title": "HFRD Test Monitor",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "TargetTestId", "label": "Test Identifier", "query": "label_values(testid)" },
   {
    "name": "channelId",
    "label": "Channel ID",
    "query": "metrics(hfrd_channel_.*_height)"
   }
  ]
 },
 "panels": [
  {
   "title": "Channel Create",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max_over_time(hfrd_channel_create_timer_count[$__range]))"
    }
   ]
  },
  {
   "title": "Channel Join",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max_over_time(hfrd_channel_join_timer_count[$__range]))"
    }
   ]
  },
  {
   "title": "Chaincode Install",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max_over_time(hfrd_chaincode_install_timer_count[$__range]))"
    }
   ]
  },
  {
   "title": "Chaincode Instantiate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max_over_time(hfrd_chaincode_instantiate_timer_count[$__range]))"
    }
   ]
  },
  {
   "title": "channel ${channelId} height",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "hfrd_channel_${channelId}_height_gauge"
    }
   ]
  },
  {
   "title": "Total Succ Transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hfrd_chaincode_invoke_timer_count{testid=\"[[TargetTestId]]\"})"
    }
   ]
  },
  {
   "title": "Total Fail Transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(hfrd_chaincode_invoke_fail_counter{testid=\"[[TargetTestId]]\"})"
    }
   ]
  },
  {
   "title": "TPS(chaincode invoke commit and sent rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hfrd_chaincode_invoke_counter_ps{testid=\"[[TargetTestId]]\"})",
     "legendFormat": "Commit Rate"
    },
    {
     "expr": "sum(hfrd_chaincode_invoke_sent_counter_ps{testid=\"[[TargetTestId]]\"})",
     "legendFormat": "Endorsement Rate"
    }
   ]
  },
  {
   "title": "CC Request time Max, Avg and Min (in ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(hfrd_chaincode_invoke_timer_max{testid=\"[[TargetTestId]]\"})"
    },
    {
     "expr": "avg(hfrd_chaincode_invoke_timer_mean{testid=\"[[TargetTestId]]\"})"
    },
    {
     "expr": "min(hfrd_chaincode_invoke_timer_min{testid=\"[[TargetTestId]]\"})"
    }
   ]
  },
  {
   "title": "proposal and broadcast latencies(in ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(hfrd_chaincode_invoke_proposal_timer_mean{testid=\"[[TargetTestId]]\"})"
    },
    {
     "expr": "avg(hfrd_chaincode_invoke_broadcast_timer_mean{testid=\"[[TargetTestId]]\"})"
    }
   ]
  }
 ]
}