{
 "title": "System Meters",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "NodeNames", "label": "Node Name", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{hostname=\"[[NodeNames:raw]]\"}",
     "legendFormat": "Load1"
    },
    {
     "expr": "node_load5{hostname=\"[[NodeNames:raw]]\"}",
     "legendFormat": "Load5"
    },
    {
     "expr": "node_load15{hostname=\"[[NodeNames:raw]]\"}",
     "legendFormat": "Load15"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\",hostname=\"[[NodeNames:raw]]\"}[5m]))*100",
     "legendFormat": "CPU Usage (%)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_network_receive_bytes_total{hostname=\"[[NodeNames:raw]]\"})/1000",
     "legendFormat": "Received Data (KB)"
    }
   ]
  },
  {
   "title": "Disk Activities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_read_bytes_total{hostname=\"[[NodeNames:raw]]\"})/1000000000",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(node_disk_written_bytes_total{hostname=\"[[NodeNames:raw]]\"})/1000000000",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{hostname=\"[[NodeNames:raw]]\"}/1000000000",
     "legendFormat": "Free (GB)"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=\"[[NodeNames:raw]]\"}/1000000000",
     "legendFormat": "Available (GB)"
    }
   ]
  }
 ]
}